name: The Cruelest Animal
favicon: null
layout_spectrum: 0.5401166919618845
typography_spectrum: 0.5860287589021027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.38064807769842446
  lightness: 0.7032221960835159
  saturation: 0.9822051154915243
  rhythmicContrast: 0.8086271400097758
purpose: []
